# -*- coding: utf-8 -*-
"""
chemdataextractor.relex.utils.py
Regular expressions for entity extraction and seed tuples

"""
from ..model import Compound, NeelTemperature, CurieTemperature
from .settings.settings import prefix_weight, middle_weight, suffix_weight
import numpy as np

# Compound regex
compound_wildcard_regex = r'\b(.+)\s?'  #r'((?:\b[\w\.\=\-\(\[\)\]]+(?:\b|\s))+)'
# Temperature value and unit extraction regex
temp_value_regex = r'((?:(?:[\+\-–∼−]?\d+(?:\.\d+)?\s?[\(\-––-∼–−±∓⨤⨦±±]\s?\d+(?:\.\d+)?[\)]?)|(?:[\<\>\≤\≥]?[\-∼–\–−]?[\+\-–∼−]?\d+(?:\.\d+)?)))'
# Neel temperature extraction specifier regex
neel_temperature_specifier_regex = r'((?:T(?:N|n)(?:eel|éel|èel)?(?:1|2)?)|(?:(?:N|n)(?:eel|éel|èel)(?:\s(?:ordering|critical))?(?:\s)(?:temp\.|temperature(?:s)?)),?(?:\s),?(?:(?:(?:(?:\(T|T)(?:N|n)(?:eel|éel|èel)?(?:1|2)?)[\)]?)?))'
# Curie temperature extraction specifier regex
curie_temperature_specifier_regex = r'((?:T(?:C|c)(?:urie)?(?:1|2)?)|(?:(?:C|c)(?:urie)(?:\s(?:ordering|critical))?(?:\s)(?:temp\.|temperature(?:s)?)),?(?:\s),?(?:(?:(?:(?:\(T|T)(?:C|c)(?:urie)?(?:1|2)?)[\)]?)?))'
# Unit regex
temp_unit_regex = r'\s((?:°C)|K)'
# seeds
neel_seeds = [("BiCrO3", "111", "K"),
              ("BiMn0.2Cr0.8O3", "74", "K"),
              ("BiMn0.4Cr0.6O3", "95", "K"),
              ("Nickel oxide (NiO)", "523", "K"),
              ("nickel oxide", "523", "K"),
              ("NiO", "523", "K"),
              ("TlNiO3", "105", "K"),
              ("YNiO3", "145", "K"),
              ("LuNiO3", "130", "K"),
              ("EuPdSn", "13", "K"),
              ("SrFeO2.50", "673", "K"),
              ("SrFeO2.50", "715", "K"),
              ("SrFeO2.5", "700", "K"),
              ("SrFeO2.75", "220", "K"),
              ("Co3O4", "33", "K"),
              ("RBa2Cu3O7", "2.2", "K"),
              ("LaCrO3", "320", "K"),
              ("MIL-53as", "65", "K"),
              ("MIL-53lt", "55", "K"),
              ("CaM2O4", "160", "K"),
              ("CaM2O4", "220", "K"),
              ("SrFeO2.50", "685", "K"),
              ("LaFeO3", "750", "K"),
              ("Tb", "2.1", "K"),
              ("Sr2CoMoO6", "350-370", "K"),
              ("CoO", "290", "K"),
              ("Dy", "179", "K"),
              ("Dy2O3", "1.2", "K"),
              ("MnTe6O13", "13", "K"),
              ("CoTe6O13", "21", "K"),
              ("Co2Te3O8", "70", "K"),
              ("Ba2LnRuO6", "30-117", "K"),
              ("Fe(PO3)3", "7.8", "K"),
              ("LaFeO3", "477", "°C"),
              ("α-Mn2O3", "79", "K"),
              ("[{Cu(3-CNpy)2(H2O)}2{Cu(3-CNpy)2(H2O)2}{W(CN)8}2] (3-CNpy = 3-cyanopyridine)", "8.0", "K"),
              ("[{Cu(4-CNpy)2}2{Cu(4-CNpy)2(H2O)2}{W(CN)8}2]·6H2O (4-CNpy = 4-cyanopyridine)", "4.4", "K"),
              ("MnO", "122", "K"),
              ("Cr(PO3)3", "4.2", "K"),
              ("Fe(PO3)3 metaphosphate", "9", "K"),
              ("NaFeP2O7", "29.0", "K"),
              ("LiFeP2O7", "22", "K"),
              ("geothite", "400", "K"),
              ("[C5N2H14]2[FeIII2F2(HPO4)4]·2H2O", "200", "K"),
              ("[C5N2H14][FeIII4(H2O)4F2(PO4)4]", "175", "K"),
              ("Ca2.5Sr0.5GaMn2O8", "150", "K"),
              ("β-(BDA-TTP)2FeCl4", "8.5", "K"),
              ("Ba2PrRuO6", "117 ± 3", "K"),
              ("Ba2PrRu0.90Cu0.10O6", "110", "K"),
              ("α-Mn2O3", "80", "K"),
              ("α-Mn2O3", "90", "K"),
              ("MnO", "118", "K"),
              ("manganese oxalate", "2.6", "K"),
              ("BiFeO3", "643", "K"),
              ("α-Fe2O3", "677", "°C"),
              ("β-Co(OH)2", "12.3", "K"),
              ("La2CoRuO6", "25", "K"),
              ("LaCaCORuO6", "96", "K"),
              ("LaSrCoRuO6", "85", "K"),
              ("Sr2CoB′O6", "30", "K"),
              ("Ba2CoTeO6", "19", "K"),
              ("Sr2CoSbO5.63", "14", "K"),
              ("Ca2CoTeO6", "10", "K"),
              ("Sr2CoTeO6", "15", "K"),
              ("Sr2CoWO6", "24", "K"),
              ("CpNi(dmit)", "27", "K"),
              ("CpNi(dsit)", "18", "K"),
              ("NaFeP2O7", "29", "K"),
              ("Na3Fe2(PO4)3", "47", "K"),
              ("FePO4", "15", "K"),
              ("[Fe2(HPO4)4]·C2N2H10", "30", "K"),
              ("[Fe(HPO4)2]·NH4", "18", "K"),
              ("ULM-4", "25", "K"),
              ("[Fe2(OH)(H2O)(PO4)2]·NH4·H2O", "22", "K"),
              ("[Fe4O(PO4)4]·C2N2H10·H2O", "12", "K"),
              ("[CoPO4]·0.5C2N2H10", "2", "K"),
              ("Na[Co2(PO4)2]·NH4·H2O", "6", "K"),
              ("Na7[Mn5F13(PO4)3(H2O)3]", "3.3", "K"),
              ("[Mn6(HPO4)4(PO4)2(H2O)2]·C4N2H12·H2O", "2.5", "K"),
              ("Na4[Ni3(PO4)2(P2O7)]", "12", "K"),
              ("NH4[FeBP2O8(OH)]", "17", "K"),
              ("Co3[Co(CN)5]2·8H2O", "38", "K"),
              ("[Fe3(HPO4)2(PO4)(C2O4)2]·H3DETA", "45", "K"),
              ("[Co(im)2]·0.5py", "13.1", "K"),
              ("LiFePO4", "52", "K"),
              ("LiMnPO4", "35", "K"),
              ("H2MnOPO4", "35", "K"),
              ("LiMnPO4", "29.5", "K"),
              ("[N(C2H5)(n-C3H7)(n-C4H9)(n-C5H11)][MnIIFeIII(ox)3]", "29", "K"),
              ("(MDT-TS)(AuI2)0.441", "50", "K"),
              ("Iron phenylphosphonate", "21.5", "K"),
              ("CoO", "-3 ± 10", "°C"),
              ("Ba2CoS3", "46", "K"),
              ("(DBrETSe)2FeBr4", "7.5", "K"),
              ("(DIETSe)2FeBr4", "7.0", "K"),
              ("TlNiO3", "104", "K"),
              ("RNiO3 series", "200", "K"),
              ("Sr2Al1.07Mn0.93O5", "105", "K"),
              ("Ca2AlMnO57", "152", "K"),
              ("Sr2GaMnO5.14", "183", "K"),
              ("(CH3NH2)K3C60", "10", "K"),
              ("(NH3)K3C60", "37", "K"),
              ("(NH3)KRb2C60", "76", "K"),
              ("Co2(OH)PO4", "70", "K"),
              ("Sr2CrSbO6", "12", "K"),
              ("LaCrO3", "282", "K"),
              ("Sr2FeWO6", "37", "K"),
              ("Sr2FeSbO6", "37", "K"),
              ("YMnO3", "80", "K"),
              ("BiFeO3", "670", "K"),
              ("HoMnO3", "75", "K"),
              ("YCrO3", "140", "K"),
              ("Fe2CoO4", "455-570", "°C"),
              ("Fe1.5Co1.5O4", "455-570", "°C"),
              ("FeCo2O4", "455-570", "°C"),
              ("Cr2Se0.71O2.30", "43", "K"),
              ("FeO", "200", "K"),
              ("[Ni(L16)(NCS)(μ-NCS)]n [L16 = N-1-(1-pyridin-2-yl-ethylidine)propane-1,3-diamine]", "3.5", "K"),
              ("Chromium sesquiselenide", "43", "K"),
              ("chromium sesquioxide", "307.5", "K"),
              ("Cr2Se0.7O2.3nanoparticles", "11", "K"),
              ("Cr2Se3", "43", "K"),
              ("Cr2O3", "307", "K"),
              ("Co2(hypa)2(4,4′-bpy) (Fig. 24 (XI)), hypa = hydroxyphenylacetate", "15.2", "K"),
              ("Co(HCOO)2(4,4′-bpy)·nH2O", "7.4", "K"),
              ("Co(HCOO)2(4,4′-bpy)·nH2O", "3", "K"),
              ("ZnFe2O4", "9-11", "K"),
              ("K2(C10H8)2(THF)", "28.6", "K"),
              ("hematite", "955", "K"),
              ("eskolaite", "300", "K"),
              ("BiMnO2.99", "30", "K"),
              ("brownmillerite", "250", "°C"),
              ("[{Ru2(O2CCF3)4}2(TCNQF4)]", "95", "K"),
              ("UO2", "30.8", "K"),
              ("MnO", "116", "K"),
              ("MnO2", "84", "K"),
              ("Ba2SmMoO6", "130", "K"),
              ("α-Fe2O3", "960", "K"),
              ("Ba8Hg3U3S18", "59", "K"),
              ("La2U2Se9", "5", "K"),
              ("cobalt hydroxides", "18-37", "K"),
              ("Sr2Co2O5", "570", "K"),
              ("Sr2Fe2O5", "700", "K"),
              ("GdS", "50", "K"),
              ("BiFeO3", "397", "°C"),
              ("Ce2FeO2Se2", "171", "K"),
              ("CeFeOAs", "140", "K"),
              ("UN", "53", "K"),
              ("[Co(SCN)2(bte)]", "2.9", "K"),
              ("β-Co[N(CN)2]2", "8.9", "K"),
              ("Co4(OH)5(1a)0.5,H2O", "9", "K"),
              ("MY10 ⊂ Co", "6.8", "K"),
              ("MO ⊂ Co", "14.3", "K"),
              ("MR ⊂ Co", "16.8", "K"),
              ("OrangeIV ⊂ Co", "18.2", "K"),
              ("Mn3[Fe(CN)6]2", "9.9", "K"),
              ("K0.2Mn1.4[Cr(CN)6]", "99", "K"),
              ("Cr3[Cr(CN)6]2·6H2O", "219", "K"),
              ("Cr3[Cr(CN)6]2·10H2O", "240", "K"),
              ("[Mn(HL)(H2O)]2Mn[Mo(CN)7]2·2H2O", "85", "K"),
              ("Fe(TCNE)2·nCH2Cl2", "100", "K"),
              ("SmFeSb3", "3.1", "K"),
              ("GdFeSb3", "7.3", "K"),
              ("TbFeSb3", "8.6", "K"),
              ("TbFeSb3", "8.8", "K"),
              ("BiFeO3", "673", "K"),
              ("TeNiO3", "130", "K"),
              ("SeNiO3", "104", "K"),
              ("BFO", "643", "K"),
              ("Fe2O3", "260", "K"),
              ("FeO", "198", "K"),
              ("LiFePO4", "50", "K"),
              ("NiO", "520", "K"),
              ("EuTe", "9.6", "K"),
              ("BiMnFe2O6", "212", "K"),
              ("BiMn0.9Fe2.1O6", "224", "K"),
              ("BiMn1.1Fe1.9O6", "204", "K"),
              ("SrMnO3", "260", "K"),
              ("LaMnO3", "140", "K"),
              ("Co0.85Se", "25", "K"),
              ("NiO", "525", "K"),
              ("FeWO4 microcrystals", "62.9", "K"),
              ("SrCoO2.5 brownmillerite", "537", "K"),
              ("Cs3C60", "2.2", "K"),
              ("lepidocrocite", "50", "K"),
              ("[Co(bIM)(acetate)] (bIM = benzimidazole)", "13.0", "K"),
              ("SrTcO3", "1000", "K"),
              ("CaMnO3", "123", "K"),
              ("Ca4Mn3O10", "125", "K"),
              ("YMnO3", "75", "K"),
              ("Li3Ni2SbO6", "15", "K"),
              ("Li1−3xFexNiPO4", "25", "K"),
              ("LiFeP2O7", "27", "K"),
              ("FeP2O7", "12.5", "K"),
              ("ZnMnO3", "18", "K"),
              ("Schafarzikite", "45", "K"),
              ("Cr2O3", "308", "K"),
              ("LiCoPO4", "23", "K"),
              ("LiNiPO4", "23", "K"),
              ("Co3O4", "40", "K"),
              ("Co3O4 nanocrystals", "26", "K"),
              ("Co3O4 nanoparticles", "15 ± 2", "K"),
              ("[Co(m-dtab)Br2]n", "2.9", "K"),
              ("[Ni(m-dtab)2Br2]n", "2.6", "K"),
              ("Er2Si2O7", "1.9", "K"),
              ("Er2Si2O7", "2.5", "K"),
              ("LaMnO3", "143", "K"),
              ("BiFe0.5Mn0.5O3", "240", "K"),
              ("Bi0.5La0.5Fe0.5Mn0.5O3 (BLFMO)", "220", "K"),
              ("Bi0.5Sr0.5Fe0.5Mn0.5O3 (BSFMO)", "226", "K"),
              ("CaFeO2.5", "725", "K"),
              ("Mn", "35", "K"),
              ("WZ-MnS nanowires", "30", "K"),
              ("WZ-MnSe nanoparticles", "64", "K"),
              ("cobalt oxide", "298", "K"),
              ("BiFeO3", "640", "K"),
              ("K0.8Fe1.6Se2", "559", "K"),
              ("LaSrNi0.5Ru0.5O4", "125", "K"),
              ("La2CoRuO6", "26", "K"),
              ("La2NiRuO6", "32", "K"),
              ("Sr3Fe2O5", "296", "K"),
              ("CeMnAsO", "360", "K"),
              ("BaTcO3", "1200", "K"),
              ("Ba2PnFeS5 (Pn = Sb, Bi)", "13", "K"),
              ("Ba2PnFeS5 (Pn = Sb, Bi)", "35", "K"),
              ("Mn2O3", "40", "K"),
              ("ZnFe2O4", "10.5", "K"),
              ("Sr2Fe2O5", "693", "K"),
              ("Sr4Fe4O11", "232", "K"),
              ("Cu2MnSnS4", "6-8.8", "K"),
              ("Cu2FeSnS4", "6-8.8", "K"),
              ("Ni(OH)2", "30", "K"),
              ("La2O2SO4", "60", "K"),
              ("α-Fe2O3", "953", "K"),
              ("α-Fe2O3", "955", "K"),
              ("Mn(AOT)2", "60", "K"),
              ("FeP nanoparticles", "110", "K"),
              ("FeP", "120", "K"),
              ("Eu2O3 NBs", "46", "K"),
              ("Tb2PdSi3", "23", "K"),
              ("CoO", "291", "K"),
              ("CuO", "230", "K"),
              ("Fe2O3", "960", "K"),
              ("β-Ni(OH)2", "25", "K"),
              ("V6O13", "155", "K"),
              ("Sr2Cu(PO4)2", "0.085", "K"),
              ("Ba2Ni(PO4)2", "5", "K"),
              ("Ba2Co(PO4)2", "5", "K"),
              ("Ba2Mn(PO4)2", "5", "K"),
              ("Pb2Ni(PO4)2", "4", "K"),
              ("YFMO", "328", "K"),
              ("La2BaFe2O5F4", "500", "K"),
              ("DyFeO3", "645", "K"),
              ("Dy", "4", "K"),
              ("YCr0.5Fe0.5O3", "260", "K"),
              ("YFeO3", "640", "K"),
              ("YFe0.5Cr0.5O3", "246", "K"),
              ("mesoporous Co3O4", "30", "K"),
              ("CoO", "298", "K"),
              ("non-magnetic Cr metals", "311", "K"),
              ("TNiON", "523", "K"),
              ("CuO", "220", "K"),
              ("Ni(OH)2", "22.5", "K"),
              ("RMn2O5", "39-45", "K"),
              ("DyCrO3 nanoplatelets", "144", "K"),
              ("DyCrO3 nanoplatelets", "146", "K"),
              ("Cr3+ ions", "142", "K"),
              ("LiMn1.5Ni0.5O4", "12", "K"),
              ("LiMnPO4", "32", "K"),
              ("PrCrO3", "3", "K"),
              ("Co3O4 nanoparticles", "25", "K"),
              ("Co3O4 nanoparticles", "31", "K"),
              ("Sr2MnGe2O7", "4.4", "K"),
              ("LaCrO4", "20", "K"),
              ("LaMnAsO", "317", "K"),
              ("CoO", "293", "K"),
              ("copper acetate", "280", "K"),
              ("MnNb2O6", "4.4", "K"),
              ("hematite", "950", "K"),
              ("Li2FeSiO4", "24", "K"),
              ("Li2FeSiO4", "20", "K"),
              ("Bismuth ferrite (BiFeO3)", "367", "°C,"),
              ("α-TiCl3", "165", "K"),
              ("Fe1-xS", "315", "°C,"),
              ("YMn2", "100", "K"),
              ("ZnCr2S4", "15", "K"),
              ("ZnCr2S4", "8", "K"),
              ("MnF2", "67", "K"),
              ("Pb(Fe2/3W1/3)O3", "340", "K"),
              ("Fe", "85", "K"),
              ("Pr", "11", "K"),
              ("CoNb2O6", "2.95", "K"),
              ("Fe-rich Sr2Fe1.33Mo0.67O6", "250", "K"),
              ("Sr2FeMoO6", "750", "K"),
              ("Sr2Fe(Fe0.33Mo0.67)O6", "250", "K"),
              ("Gd4O4Se3", "7-9", "K"),
              ("Dy4O4Se3", "7-9", "K"),
              ("Tb4O4Se3", "7-9", "K"),
              ("A4O4Se3", "8-11", "K"),
              ("Ba2YRuO6", "37", "K"),
              ("Ca2Cr2O5", "200", "K"),
              ("TlCrO3", "89", "K"),
              ("TlCrO3", "87.0", "K"),
              ("TlCrO3", "89.3", "K"),
              ("ScCrO3", "68.8", "K"),
              ("ScCrO3", "73.0", "K"),
              ("TlCr0.9557Fe0.05O3", "87.5", "K"),
              ("LaCrO3", "288", "K"),
              ("LuCrO3", "112", "K"),
              ("InCrO3", "93", "K"),
              ("TlFeO3", "560", "K"),
              ("LuFeO3", "625", "K"),
              ("TlMnO3", "92", "K"),
              ("PrMnO3", "100", "K"),
              ("AnBnO3n−2 (B = Fe) ferrites", "625-630", "K"),
              ("Pb2.4Ba2.6Fe2Sc2TiO13", "45", "K"),
              ("α-Fe2O3", "948", "K"),
              ("α-Fe2O3", "963", "K"),
              ("iron monoxide", "198", "K"),
              ("Yb1−xDyxMnO3 (0.1 ≤ x ≤ 0.5)", "10", "K"),
              ("h-YbMnO3", "88", "K"),
              ("o-DyMnO3", "6.5", "K"),
              ("h-Yb0.5Dy0.5MnO3", "4.4", "K"),
              ("BiFeO3 (BFO)", "640", "K"),
              ("BiFeO3 (BFO)", "643", "K"),
              ("BFO", "640", "K"),
              ("FexO core", "240", "K"),
              ("FexO", "200", "K"),
              ("Ni3(BO3)2 nanorods and nanospindles", "44-47", "K"),
              ("γ-Fe2O3", "800", "K"),
              ("CoNb2O6", "3", "K"),
              ("NiNb2O6", "6", "K"),
              ("LiFe1−xMnxPO4", "50 ± 2", "K"),
              ("BiCoO3", "470", "K"),
              ("LFO", "738", "K"),
              ("zinc ferrite", "10", "K"),
              ("Co2P-type", "260-285", "K"),
              ("NiAs2O4", "53", "K"),
              ("NiSb2O4", "47", "K"),
              ("MnSb2O4", "55", "K"),
              ("CoSb2O4", "79", "K"),
              ("Hematite", "956", "K"),
              ("hematite", "956", "K"),
              ("LiMnPO4", "34", "K"),
              ("Hematite (α-Fe2O3)", "948", "K"),
              ("CuO", "213", "K"),
              ("15R-BaFeF0.2O2.42", "700", "K"),
              ("LaSrCrO4", "242", "K"),
              ("Ca2MnO4", "110", "K"),
              ("YsrCrO4", "170", "K"),
              ("YCaCrO4", "140", "K"),
              ("Tb0.961Mn2", "46", "K"),
              ("Tb0.944Mn2", "40", "K"),
              ("Tb", "229", "K"),
              ("YMn2O5", "39-45", "K"),
              ("TbMn2O5", "39-45", "K"),
              ("DyMn2O5", "39-45", "K"),
              ("GdMn2O5", "39-45", "K"),
              ("RMn2O5 (R = Bi, Eu and Dy)", "39-45", "K"),
              ("5 nm CuO assembly", "30", "K"),
              ("FeO", "195", "K"),
              ("Mn0.29Fe0.71O NPs", "173", "K"),
              ("Mn0.50Fe0.50O NPs", "157", "K"),
              ("LCP", "22", "K"),
              ("LFP", "52", "K"),
              ("Rare earth orthoferrites RFeO3", "620", "K"),
              ("HMO", "24.5", "K"),
              ("cobalt vanadate", "71", "K"),
              ("La3Fe(MoO4)6", "6.6", "K"),
              ("Zn0.2Mn0.8PS3", "54", "K"),
              ("NdMnO3", "67", "K"),
              ("NdMnO3", "67.2", "K"),
              ("PrCrO3", "238.7", "K"),
              ("PrCrO3", "198.52", "K"),
              ("NdCrO3", "219.6", "K"),
              ("Bi2Fe4O9", "250", "K"),
              ("Ca0.8Sr0.2MnO3", "145", "K"),
              ("Fe1−xO (wüstite)", "200", "K"),
              ("CuO nanoparticles", "30", "K"),
              ("CuO nanoparticles", "13", "K"),
              ("permalloy–FeTiO3", "59", "K"),
              ("FeTiO3", "59", "K"),
              ("FTO", "59", "K"),
              ("GFO films", "360", "K"),
              ("Sm3Mn0.5GeSe7", "13", "K"),
              ("Sm3Fe0.5SiSe7", "24", "K"),
              ("nickel hydroxide", "23", "K"),
              ("CuFeO2 crystals", "12", "K"),
              ("Ni0.5Zn0.5Fe2O4", "592", "K"),
              ("Ca2Fe2O5", "725", "K"),
              ("Ca2Fe2O5", "770", "K"),
              ("nanostructured Ca2Fe2O5", "820", "K"),
              ("Ca2Fe2O5", "775", "K"),
              ("MnSb2Se4", "20", "K"),
              ("Y2Ru2O7", "77", "K"),
              ("SrFeO2", "473", "K"),
              ("V3S4", "8", "K"),
              ("V5S8", "32", "K"),
              ("LaFeO3", "740", "K"),
              ("β-Co(OH)2", "12.5", "K"),
              ("iron fluoride system", "192", "K"),
              ("BFS–BT ceramic", "400", "K"),
              ("BiFeO3", "370", "°C"),
              ("BFO", "370", "°C"),
              ("ZnCr2O4", "16", "K"),
              ("CrCl3", "16.8", "K"),
              ("HoFeO3", "640", "K"),
              ("Mn0.8Co0.2Sb2O4", "120", "K"),
              ("FexCo1−xSb2O4", "55", "K"),
              ("CuSe2O5", "17", "K"),
              ("CrN", "286", "K"),
              ("Chalcopyrite (CuFeS2)", "550", "°C"),
              ("β-Fe2O3", "119", "K"),
              ("LuMnO3", "90", "K"),
              ("SFO5", "74", "K"),
              ("SCO5", "45", "K"),
              ("Mn5O8", "136", "K"),
              ("Cd2Mn3O8", "10", "K"),
              ("Ca2Mn3O8", "60", "K"),
              ("Mn5O8", "128", "K"),
              ("Mn5O8", "133", "K"),
              ("Mn5O8", "132", "K"),
              ("Mn5O8", "131", "K"),
              ("Mn5O8", "126", "K"),
              ("Co2SiO4", "49", "K"),
              ("Co2SiO4", "49.5", "K"),
              ("MnF2", "67.4", "K"),
              ("CoA2+ ions", "40", "K"),
              ("Mg6MnO8", "5", "K"),
              ("DMO", "39", "K"),
              ("CrN", "280", "K"),
              ("MnSe", "130", "K"),
              ("C12Fe2", "26", "K"),
              ("C12Re2", "88", "K"),
              ("chalcopyrite", "823", "K"),
              ("LuMn1−xO3+δ", "90", "K"),
              ("LaFeO3", "747", "K"),
              ("Nb7Fe3B8", "240", "K"),
              ("Ta7Fe3B8", "265", "K"),
              ("o-YMnO3", "328", "K"),
              ("o-YbMn0.5Fe0.5O3", "298", "K"),
              ("BaxCr5Se8", "58", "K"),
              ("NP-CePdSn", "7.5", "K"),
              ("HP-CePdSn", "5", "K"),
              ("TbB50", "17.5", "K"),
              ("ErB50", "4.6", "K"),
              ("HoCrO3", "141", "K"),
              ("HoCrO3", "100.28", "K"),
              ("iron(III) oxalate tetrahydrate", "25", "K"),
              ("Fe", "12", "K"),
              ("Co", "10.17", "K"),
              ("Mn", "3.4", "K"),
              ("α-MnS", "150", "K"),
              ("BaLa2MnS5", "58.5", "K"),
              ("MnSb2Se4", "20.0", "K"),
              ("PbMnInS5", "25.0", "K"),
              ("Sm2Mn3Sb4S12", "40.0", "K"),
              ("Cs[Yb9Mn4Se18]", "25.0", "K"),
              ("Mn4Gd2S7", "70", "K"),
              ("Na4CoTeO6", "3", "K"),
              ("Na4NiTeO6", "6.5", "K"),
              ("NiSb2O6", "2.5", "K"),
              ("CoSb2O6", "11", "K"),
              ("BiFeO3", "647", "K"),
              ("γ-Fe2O3", "950", "K"),
              ("[Co2(tda)(tz)(H2O)2]·H2O", "3.5", "K"),
              ("[Co2(tda)(tz)(H2O)2]·H2O", "4", "K"),
              ("SFWO", "37", "K"),
              ("spinel zinc ferrite", "10", "K"),
              ("Mn", "85", "K"),
              ("YbMnO3", "85", "K"),
              ("Yb", "3.5", "K"),
              ("Co0.2Zn0.8Fe2O4", "200", "K"),
              ("Sm", "100", "K"),
              ("YCO", "140", "K"),
              ("SmCrO3", "191", "K"),
              ("Mn", "100", "K"),
              ("Mn4Nb2O9", "108.4", "K"),
              ("α-Fe2O3", "996", "K"),
              ("FePbBiO4", "24", "K"),
              ("FeSb2O4", "46", "K"),
              ("Cr2CFCl", "400", "K"),
              ("Cr2CClBr", "400", "K"),
              ("Cr2CHCl", "400", "K"),
              ("Cr2CHF", "400", "K"),
              ("Cr2CFOH", "400", "K"),
              ("bismuth ferrites", "370", "°C"),
              ("Bi1−xRExFeO3", "370", "°C"),
              ("RE–BFO", "370", "°C"),
              ("Mn2+", "8.0", "K"),
              ("Co2+", "15.7", "K"),
              ("Ni2+", "34", "K"),
              ("BiFeO3", "645", "K"),
              ("GeFe3Ny", "80", "K"),
              ("Ba2NdMoO6", "15", "K"),
              ("LuVO4", "2.4", "K"),
              ("Nd5Ge3", "50", "K"),
              ("Cr", "308", "K"),
              ("NiCl2", "50", "K"),
              ("MnTe", "307", "K")]
curie_seeds = [("Co", "1394", "K"),
               ("cobalt", "1394", "K"),
               ("Cobalt (Co)", "1394", "K"),
               ("Nickel", "358", "°C"),
               ("nickel", "358", "°C"),
               ("Ni", "358", "°C"),
               ("Ge0.95Mn0.05 quantum dots", "400", "K"),
               ("(Bi0.5Na0.5)TiO3 [BNT]", "320", "°C"),
               ("(Bi0.5Na0.5)TiO3", "320", "°C"),
               ("BNT", "320", "°C"),
               ("TGS", "49", "°C"),
               ("(NH2CH2COOH)3·H2SO4", "49", "°C"),
               ("triglycine sulfate", "49", "°C"),
               ("4(p-Chlorobenzylideneamino)-2,2,6,6-tetramethylpiperidine-N-oxyl", "0.28", "K"),
               ("Iron", "1043", "K"),
               ("Fe", "1043", "K"),
               ("Cobalt", "1400", "K"),
               ("Co", "1400", "K"),
               ("Nickel", "627", "K"),
               ("Ni", "627", "K"),
               ("Gadolinium", "292", "K"),
               ("Gd", "292", "K"),
               ("Dysprosium", "88", "K"),
               ("Dy", "88", "K"),
               ("Manganese bismuthide", "630", "K"),
               ("MnBi", "630", "K"),
               ("Manganese antimonide", "587", "K"),
               ("MnSb", "587", "K"),
               ("Chromium(IV) oxide", "386", "K "),
               ("CrO2", "386", "K"),
               ("Manganese arsenide", "318", "K"),
               ("MnAs", "318", "K"),
               ("Europium oxide", "69", "K"),
               ("EuO", "69", "K"),
               ("Iron(III) oxide", "948", "K"),
               ("Fe2O3", "948", "K"),
               ("Iron(II,III) oxide", "858", "K"),
               ("FeOFe2O3", "858", "K"),
               ("NiO–Fe2O3", "858", "K"),
               ("CuO–Fe2O3", "728", "K"),
               ("MgO–Fe2O3", "713", "K"),
               ("MnO–Fe2O3", "573", "K"),
               ("Yttrium iron garnet", "560", "K"),
               ("Y3Fe5O12", "560", "K"),
               ("Neodymium magnets", "583–673", "K"),
               ("Alnico", "973–1133", "K"),
               ("Samarium–cobalt magnets", "993–1073", "K"),
               ("Strontium ferrite", "723", "K"),
               ("[Mn(bispicen)]3[Cr(CN)6]2·6H2O·0.5EtOH", "17", "K"),
               ("CoCr2S4", "240", "K"),
               ("Fe2[MoIII(CN)7]·8H2O", "65", "K"),
               ("Ca1−xLaxB6 with x = 0.2", "600", "K"),
               ("Ni2(OH)3(C12H25SO3)·H2O", "18", "K"),
               ("methano[60]fullerene derivative complexed with cobaltocene", "15", "K"),
               ("BaTiO3", "120", "°C"),
               ("[60]fullerene", "500", "K"),
               ("RBa2Cu3O7 (RBCO)", "92", "K"),
               ("Sr2YRu1−xCuxO6", "45", "K"),
               ("CaMnO3", "100", "K"),
               ("Sr2NaNb5O15 (SNN)", "278", "°C"),
               ("Co5(OH)8L2·nH2O", "60", "K"),
               ("CoFe2O4", "780-800", "K"),
               ("Gd", "294", "K"),
               ("La0.65Ba0.35MnO3", "362", "K"),
               ("Sr2FeMoO6", "385", "K"),
               ("Ba2FeMoO6", "308", "K"),
               ("Ca2FeMoO6", "365", "K"),
               ("Sr2FeMoO6", "420", "K"),
               ("CoFe2O4", "500-525", "°C"),
               ("magnetite (Fe3O4)", "860", "K"),
               ("magnetite", "860", "K"),
               ("Fe3O4", "860", "K"),
               ("iron", "1040", "K"),
               ("ErCrO4", "15", "K"),
               ("TmCrO4", "18", "K"),
               ("La0.75Sr0.25MnO3 particles", "56", "°C"),
               ("La0.8Sr0.2MnO3 particles", "48", "°C"),
               ("La0.7Ca0.3CoO2.97", "175", "K"),
               ("Ce5Pb3O", "46", "K"),
               ("U compound", "62", "K"),
               ("MnGeP2", "320", "K"),
               ("MnGeAs2", "340", "K"),
               ("BiFeO3", "1103", "K"),
               ("Co1.5Fe1.5O4 bulk crystals", "417", "°C"),
               ("CoFe2O4 bulk crystals", "520", "°C"),
               ("CoII5(OH)6(SO4)2(H2O)4", "12", "K"),
               ("Co-doped ZnO films", "280", "K"),
               ("Zn1−xCoxO films", "300", "K"),
               ("Sr2CrReO6", "635", "K"),
               ("La/Ba disordered polymorph", "270", "K"),
               ("ordered polymorph", "335", "K"),
               ("cobalt", "1388", "K"),
               ("Fe1.25Pt0.75Mo3N", "225", "K"),
               ("Zn1−xCoxO", "750", "K"),
               ("Sr3Fe2MoO98", "280", "K"),
               ("Sr3Fe2UO9", "330", "K"),
               ("Sr2FeMoO6", "416", "K"),
               ("ferrofluids containing Mn and Zn", "80", "°C"),
               ("Manganese stannate (Mn2SnO4)", "53-58", "K"),
               ("Mn3O4 nanowires", "43", "K"),
               ("Mn2SnO4 nanowires", "46", "K"),
               ("cobalt–ruthenium", "370", "°C"),
               ("Co3Ru", "370", "°C"),
               ("cobalt nanoparticles", "1100", "°C"),
               ("nickel hexacyanochromate", "60", "K"),
               ("La2Ti2O7", "1500", "°C"),
               ("LiNbO3", "1500", "K"),
               ("Thiourea", "169", "K"),
               ("D = H2ca", "253", "K"),
               ("H2ba", "138", "K"),
               ("maghemite", "948", "K"),
               ("γ-Fe2O3", "948", "K"),
               ("La1−xBixMnO3+δ7,8", "80", "K"),
               ("BiMnO3", "100", "K"),
               ("Ca2CrSbO6", "16", "K"),
               ("Sr2CrWO6", "458", "K"),
               ("Sr2CrMoO6", "450", "K"),
               ("Ca analogue", "16", "K"),
               ("BaTiO3", "393", "K"),
               ("BiFeO3", "1110", "K"),
               ("La0.7Sr0.3MnO3", "371", "K"),
               ("La0.7Ca0.3MnO3.12", "260", "K"),
               ("cobalt cations", "75", "K"),
               ("ruthenium", "230", "K"),
               ("Fe1.5Rh0.5Mo3N", "30", "K"),
               ("Ca-doped manganites", "260", "K"),
               ("La–Ca–Mn–O system", "155", "K"),
               ("Co5(OH)6(SO4)2(H2O)4", "14", "K"),
               ("Co5(OH)8(trans-1,4-chdc)·4H2O", "61", "K"),
               ("[Co7(OH)12(H2O)2](C2H4(SO3)2)", "33", "K"),
               ("Fe(CH3OH)(ox)", "23", "K"),
               ("BiMnO3", "105", "K"),
               ("La1.2Bi0.8Mn2O6.20", "103", "K"),
               ("EuS nanocrystals", "15", "K"),
               ("Potassium niobate (KNbO3; KN) ceramics", "435", "°C"),
               ("LiNbO3", "583", "K"),
               ("LiTaO3", "583", "K"),
               ("BSPT", "450", "°C"),
               ("deuterated Phz–D2ca crystal", "304", "K"),
               ("Cs2AgF4", "14-15", "K"),
               ("Rb2ZnCl4", "198.3", "K"),
               ("Pb3Cr2(PO4)4 crystals", "4", "K"),
               ("CrO2", "395", "K"),
               ("cobalt", "1390", "K"),
               ("[{MnII(H2O)2}{MnII(pyrazine)(H2O)2}{NbIV(CN)8}]·4H2O.12", "48", "K"),
               ("CeTiGe3", "14", "K"),
               ("LaCrGe3", "78", "K"),
               ("SmCrGe3", "155", "K"),
               ("Fe3O4 or magnetite", "858", "K"),
               ("CoFe2O4", "793", "K"),
               ("[Cp*2Fe]+[TCNE]−", "4.8", "K"),
               ("Ga0.6Fe1.4O3 thin films", "370", "K"),
               ("[Fe(C5Me5)2][TCNE]", "4.8", "K"),
               ("[Cr(C5Me5)2][TCNE]", "2.1", "K"),
               ("[Fe(C5Me5)2][DCNQ]", "4", "K"),
               ("CoSe2", "124", "K"),
               ("Hausmannite (Mn3O4)", "42", "K"),
               ("LnOCoAs", "66", "K"),
               ("LnOCoAs", "85", "K"),
               ("Cobalt", "1388", "K"),
               ("Ni and Co nanomaterials", "350", "K"),
               ("BNT", "320", "°c"),
               ("Lead titanate perovskite (PbTiO3)", "490", "°C"),
               ("pure nickel", "631", "K"),
               ("1,2,3,5-dithiadiazolyl radicals", "36", "K"),
               ("55DMBP–H2ca", "318", "K"),
               ("55DMBP–H2ca", "345", "K"),
               ("[Fe(C5Me5)2]+[TCNE]˙− (TCNE = tetracyanoethylene)", "4.8", "K"),
               ("β-4-nitrophenylnitronyl nitroxide (β-NPNN)", "0.6", "K"),
               ("α—a metamagnet", "2.55", "K"),
               ("β—a ferromagnet", "3.1", "K"),
               ("4′-nitrotetrafluorophenyldithiadiazolyl", "1.32", "K"),
               ("4′-cyanotetrafluorophenyldithiadiazolyl", "35.5", "K"),
               ("[M(C5Me5)2][TCNZ] (M = Cr, Mn, Fe; Z = E, Q)", "8.8", "K"),
               ("[CrIII(NH3)6]3+[FeIIICl6]3−", "0.66", "K"),
               ("[CrIII(NH3)6]3+[CrIII(CN)6]3−", "2.85", "K"),
               ("MnIIBunPO3·H2O", "15", "K"),
               ("(Me4ET)xMnII[CrIIIox3]·CH2Cl2 (x ∼ 2.6)", "5.5", "K"),
               ("[Ru2(O2CBut)4]3[CrIII(CN)6]·2H2O", "37.5", "K"),
               ("[MnII(hfac)2]3102", "46", "K"),
               ("H0.2[Ru2(O2CMe)4]2.8[Cr(CN)5NO]", "4.0", "K"),
               ("HxK1−xMII[Ru2(CO3)4]·zH2O", "4.4 ± 10", "K"),
               ("MnII3[CrIII(CN)6]2·12H2O Prussian blue analog", "63", "K"),
               ("[NEt(n-Pr)(n-Bu)(n-C5H11)]MnII[CrIIIox3]", "6", "K"),
               ("[NBu4]MnII[CrIIIox3]", "6", "K"),
               ("[FeIII(C5Me5)2]MnII[CrIIIox3]", "5.3", "K"),
               ("[PPh4]MnII[CrIIIox3]", "5.9", "K"),
               ("[RuI(bipy)2Phpy]MnII[CrIIIox3]", "5.8", "K"),
               ("[IrIbipy(Phpy)2]MnII′[CrIIIox3]", "5.1", "K"),
               ("[FeII″bipy3]MII′[MIIIox3]ClO4", "4.2", "K"),
               ("[FeII″bipy3]MII′[MIIIox3]ClO4", "3.9", "K"),
               ("Ni3[Fe(CN)6]2", "24.9", "K"),
               ("[Fe(CN)6]2", "21.8", "K"),
               ("CsNi[Cr(CN)6]", "75", "K"),
               ("CsNi[Cr(CN)6]·2H2O", "90", "K"),
               ("[CN4H8]ZrF6", "383", "K"),
               ("[EtNH3]2CuCl4", "247", "K"),
               ("[EtNH3]2CuCl4", "10.2", "K"),
               ("(NH4)Zn(HCOO)3", "192", "K"),
               ("LnCrSb3 (Ln = La–Nd, Sm)", "105-125", "K"),
               ("YbCrSb3", "280", "K"),
               ("Mn3O4", "42", "K"),
               ("K0.46Na0.54NbO3", "670", "K"),
               ("Prussian blue", "5.6", "K"),
               ("VII[CrIII(CN)6]0.86·2.8H2O", "351", "K"),
               ("KIVII[CrIII(CN)6]", "376", "K"),
               ("KI0.058VII/III[CrIII(CN)6]0.79(SO4)0.058·0.93H2O", "372", "K"),
               ("lead zirconate titanate, Pb(ZrxTi1−x)O3.26–30", "300-400", "°C"),
               ("CO2", "304", "K"),
               ("NiCo2O4", "500", "°C"),
               ("Perovskite BFO", "1103", "K"),
               ("Fe3O4", "850", "K"),
               ("LSMO@siF@si-w", "340", "K"),
               ("Ag2Nb4O11 ceramics", "400", "K"),
               ("YSCO", "335", "K"),
               ("PbTiO3", "490", "°C"),
               ("Perovskite-structured lead titanate (PbTiO3, PT)", "490", "°C"),
               ("Co-doped ZnO (10% Co doping, 1% donor defects)", "18", "K"),
               ("nickel", "350", "°C"),
               ("nanocrystalline NiO", "5", "K"),
               ("La0.67Ca0.33MnO3 (LCMO)", "270", "K"),
               ("Ca0.85Sm0.15MnO3 (CSMO)", "110", "K"),
               ("La0.9Te0.1MnO3", "239", "K"),
               ("(R)- or (S)-1-phenylethylamine", "5.5", "K"),
               ("p-nitrophenyl α-nitronyl-nitroxide derivative", "0.6", "K"),
               ("[C60][TDAE] cation salt", "16", "K"),
               ("Mn3O4", "44", "K"),
               ("hollandite", "225", "K"),
               ("K2Cr8O16", "225", "K"),
               ("Potassium deficient hollandites K2−xCr8O16", "250", "K"),
               ("K2Cr8O16", "180", "K"),
               ("Fe3O4", "585", "°C"),
               ("Ag2Nb4O11", "400", "K"),
               ("V-doped ZnO nanorods", "345", "°C"),
               ("V-doped ZnO", "345", "°C"),
               ("CoS2", "116", "K"),
               ("MnFe2O4", "560", "K"),
               ("LaSr-2 × 4 manganese oxide NWs", "500", "K"),
               ("Cr2Te3", "190", "K"),
               ("CuCr2Te4", "330", "K"),
               ("PFN–PYN–PT crystal", "325", "°C"),
               ("[M3(hfipbb)2(OH)2(H2O)] with M = Co and Ni", "8", "K"),
               ("[M3(hfipbb)2(OH)2(H2O)] with M = Co and Ni", "2.5", "K"),
               ("0.20PYN–0.40PMN–0.40PT", "180", "°C"),
               ("0.165PYN–0.495PMN–0.34PT ceramics", "242", "°C"),
               ("BIT", "675", "°C"),
               ("PLN–0.49PT", "360", "°C"),
               ("PbTiO3 crystal", "490", "°C"),
               ("diisopropylammonium bromide (DPB)", "425", "K"),
               ("La0.7Sr0.3MnO3", "370", "K"),
               ("Tl2Mn2O7 oxide", "142", "K"),
               ("R2Ru2O7 pyrochlores", "100", "K"),
               ("R2Ru2O7", "80-95", "K"),
               ("R2Mn2O7", "20-.40", "K"),
               ("CaMn3O6/CaMn2O4 heterostructure nanoribbons", "50", "K"),
               ("ErCu3Mn4O12", "405", "K"),
               ("ErCu3(Mn3Fe)O12", "332", "K"),
               ("CaCu3(Mn3Fe)O12", "235", "K"),
               ("CeCu3(Mn3Fe)O12", "357", "K"),
               ("KNBN-La", "360", "°C"),
               ("La2NiMnO6 (LNMO)", "280", "K"),
               ("Co2FeSi", "1100", "K"),
               ("SrRuO3", "165", "K"),
               ("La2ZnRuO6", "165", "K"),
               ("BiScO3–PbTiO3 materials", "450", "°C"),
               ("α-K2AgF4", "13", "K"),
               ("Fe3O4 MNPs", "585", "°C"),
               ("Na0.5Bi2.5Nb2O9 (NBN)", "790", "°C"),
               ("NBN", "788", "°C"),
               ("NBN-LiLa", "751", "°C"),
               ("NBN-LiY", "842", "°C"),
               ("BiFeO3", "1100", "K"),
               ("Bi2Mn4O10", "42", "K"),
               ("potassium–sodium niobate (KNN) solid", "420", "°C"),
               ("Yb14MnSb11", "53", "K"),
               ("NiMn2O4", "72", "K"),
               ("NiMn2O4", "122", "K"),
               ("NiMn2O4", "145", "K"),
               ("NiMn2O4 nanoparticles", "126", "K"),
               ("Nd2Ti2O7", "1500", "°C"),
               ("BaTiO3", "403", "K"),
               ("PS-BTO11", "413", "K"),
               ("PS-BTO27", "413", "K"),
               ("NiFe2O4", "858", "K"),
               ("Magnetite (Fe3O4)", "858", "K"),
               ("CoFe2O4", "798", "K"),
               ("La0.82Sr0.18MnO3", "42", "°C"),
               ("LCMO", "220", "K"),
               ("ferromagnetic Nd–Fe–B", "586", "K"),
               ("Ln–TM–B", "140", "°C"),
               ("Nd2Fe14B", "312", "°C"),
               ("PbZr0.95Ti0.05O3 thin film", "222", "°C"),
               ("(α-Fe)", "1043", "K"),
               ("CrO1.90F0.10", "300", "K"),
               ("CrO1.88F0.12", "280", "K"),
               ("LSMO", "307", "K"),
               ("nickel hydroxide nanospheres", "16.5", "K"),
               ("Bismuth sodium titanate (Bi0.5Na0.5TiO3, BNT)", "320", "°C"),
               ("Sr2FeMoO6 (SFMO)", "415", "K"),
               ("Ln2Ti2O7", "1500", "°C"),
               ("La2Ti2O7 (LTO)", "1500", "°C"),
               ("bimetallic Mn–Ru2 carbonate", "3.0", "K"),
               ("Li-doped ZnO film", "546", "K"),
               ("NBT ceramics", "320", "°C"),
               ("CBNO-LiNd-ScW-0.01 ceramic", "908", "°C"),
               ("CaBi2Me2O9", "870", "°C"),
               ("Bi3TiMeO9", "943", "°C"),
               ("CBNO materials", "943", "°C"),
               ("BiFeO3", "825", "°C"),
               ("LiNbO3 (LN)", "1140", "°C"),
               ("2-phenylmalondialdehyde (PhMDA)", "400", "K"),
               ("3-hydroxyphenalenone (3-HPLN)", "400", "K"),
               ("cyclobutene-1,2-dicarboxylic acid (CBDC)", "400", "K"),
               ("semihydrogenated graphene", "278", "K"),
               ("MnS2", "225", "K"),
               ("MnSe2", "250", "K"),
               ("KNLNT", "310", "°C"),
               ("LSMO", "50", "°C"),
               ("iron oxide", "500", "°C"),
               ("LSMO epitaxial layers with non-magnetic oxide nanopyramids", "450", "°C"),
               ("LSMO nanoislands", "350", "K"),
               ("{[Mn1.5(L)(bpe)1.5]·(bpe)0.5}n", "40", "K"),
               ("Na0.5Bi0.5TiO3 ceramics", "280", "°C"),
               ("ht-Mn3(VO4)2", "55", "K"),
               ("Ca2FeReO6", "540", "K"),
               ("Sr2FeReO6", "400", "K"),
               ("Ba2FeReO6", "303", "K"),
               ("Ca2FeReO6", "522", "K"),
               ("Pb2FeReO6", "420", "K"),
               ("(K0.44Na0.52Li0.04)(Nb0.84Ta0.1Sb0.06)O3 ceramics", "264", "°C"),
               ("PKN", "460", "°C"),
               ("K2[Mn3(H2O)6][Mo(CN)7]2·6H2O15", "39", "K"),
               ("VII2[MoIII(CN)7](pyrimidine)2·4.5H2O", "110", "K"),
               ("{[Mn(dpop)]3[Mn(dpop)(H2O)][MoIII(CN)7]2·13.5H2O}n", "3", "K"),
               ("PZT based ferroelectrics", "400", "°C"),
               ("bismuth ferrite based polycrystalline ceramics", "650", "°C"),
               ("LiNbO3", "1142–1210", "°C"),
               ("GdFeO3", "2.5", "K"),
               ("substituted iron oxides", "100", "°C"),
               ("Spinel ferrite CFO", "793", "K"),
               ("La2NiMnO6 (LNMO)", "275", "K"),
               ("La2CoMnO6 (LCMO)", "200", "K"),
               ("La2CoMnO6 (LCMO)", "225", "K"),
               ("thin film samples of LCMO", "135-150", "K"),
               ("BTO", "400", "K"),
               ("STO", "105", "K"),
               ("BTO", "130", "°C"),
               ("barium titanate", "130", "°C"),
               ("V(TCNE)x·y(DCM)", "400", "K"),
               ("magnetite (Fe3O4)", "850", "K"),
               ("[NMe4][CdBr3]", "156", "K"),
               ("[MeNH3][SnCl3]", "350", "K"),
               ("Cr-polyporphyrin (Cr-PP)", "187", "K"),
               ("Mn–Pc single layer", "150", "K"),
               ("ZGNR", "10", "K"),
               ("iodo-substituted bisdiselenazolyl radical 1c", "10.5", "K"),
               ("tetragonal heavy-atom bisdiselenazolyl radical 1a", "17", "K"),
               ("Bi4Ti3O12", "675", "°C"),
               ("γ-Fe2O3", "928", "K"),
               ("ε-Fe2O3", "495", "K"),
               ("α-Fe2O3", "950", "K"),
               ("SrFe12O19", "470", "°C"),
               ("two-dimensional (2D) germanene van der Waals heterostructure (HTS)", "244", "K"),
               ("thiophene oligomers", "630", "K"),
               ("Half-silicane", "300", "K"),
               ("ZrS2", "66.02", "K"),
               ("Fe doped SnO2", "610", "K"),
               ("CrO2", "390", "K"),
               ("BaTiO3", "400", "K"),
               ("gadolinium", "293", "K"),
               ("MnO2", "50", "°C")]


def match(pi, pj):
    """ Compute match between phrases using a dot product of vectors
    :param pi Phrase or pattern
    :param pj phrase or pattern
    # add weights to dot products to put more emphasis on matching the middles
    """

    if pi.order != pj.order:
        return 0

    #print(pi.as_string(), pj.as_string())

    number_of_middles_i = pi.number_of_entities - 1
    number_of_middles_j = pj.number_of_entities - 1
    if number_of_middles_i != number_of_middles_j:
        return 0


    prefix_i = pi.elements['prefix']['1']['vector']
    middles_i = [pi.elements['middles'][m]['vector'] for m in pi.elements['middles'].keys()]
    suffix_i = pi.elements['suffix']['1']['vector']

    prefix_j = pj.elements['prefix']['1']['vector']
    middles_j = [pj.elements['middles'][m]['vector'] for m in pj.elements['middles'].keys()]
    suffix_j = pj.elements['suffix']['1']['vector']

    if len(prefix_i) == 0 and len(prefix_j) == 0:
        prefix_dot_prod = 1.0
    else:
        prefix_dot_prod = np.dot(prefix_i, prefix_j)

    middle_dot_prod = []
    for i in range(0, len(middles_i)):
        if len(middles_i[i]) == 0 and len(middles_j[i]) == 0:
            middle_dot_prod.append(1.0)
        elif len(middles_i[i]) != len(middles_j[i]):
            middle_dot_prod.append(0)
        else:
            #print(i, pi.elements['middles'], pj.elements['middles'])
            #print(middles_i, middles_j)
            m_dot = np.dot(middles_i[i], middles_j[i])
            middle_dot_prod.append(m_dot)

    if len(suffix_i) == 0 and len(suffix_j) == 0:
        suffix_dot_prod = 1.0
    else:
        suffix_dot_prod = np.dot(suffix_i, suffix_j)

    sim = (prefix_weight * prefix_dot_prod) + ((middle_weight/number_of_middles_j) * sum(middle_dot_prod)) + (suffix_weight * suffix_dot_prod)
    return sim

def matches_coincide(m1, m2):
    """ Test to see if two match objects are the same or overlap based on start, end and span"""
    if m1.start() == m2.start() and m1.end() == m2.end() and m1.span() == m2.span():
        return True
    elif m2.start() >= m1.start() and m2.end() <= m1.end():
        return True
    elif m1.start() >= m2.start() and m1.end() <= m2.end():
        return True
    return False


def snowball_to_cde(rec):
    """Convert Snowball dict to CDE records"""
    # convert snowball records to CDE records
    c = Compound(names=[rec['Names']])
    if rec['Type'] == 'neel_temperatures':
        nt = NeelTemperature(value=rec['Extracted Value'], units=rec['Extracted Units'], confidence=rec['Confidence'])
        c.neel_temperatures.append(nt)
    elif rec['Type'] == 'curie_temperatures':
        ct = CurieTemperature(value=rec['Extracted Value'], units=rec['Extracted Units'], confidence=rec['Confidence'])
        c.curie_temperatures.append(ct)

    return c
